messages =
(
  {
    description = "";
    format = "Error parsing JSON document: !%1!\n";
    gid = "90-2";
    id = "1";
    key = "Error parsing JSON document: %s\n";
    modified_format_str = "@90-2@%s";
    notes = "";
    owner = "brianc";
    reference_cnt = "1";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "ERROR";
    tags = "";
  },
  {
    description = "";
    format = "Failed to merge top-block module '!%1!' into sub-block instance '!%2!'.!%3!\n";
    gid = "90-3";
    id = "2";
    key = "Failed to merge top-block module '%s' into sub-block instance '%s'.%s\n";
    modified_format_str = "@90-3@%s%s%s";
    notes = "";
    owner = "brianc";
    reference_cnt = "1";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "CRITICALWARNING";
    tags = "";
  },
  {
    description = "";
    format = "Failed to read file '!%1!'.\n";
    gid = "90-4";
    id = "3";
    key = "Failed to read file '%s'.\n";
    modified_format_str = "@90-4@%s";
    notes = "";
    owner = "brianc";
    reference_cnt = "1";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "ERROR";
    tags = "";
  },
  {
    description = "";
    format = "Failed to split sub-block instance '!%1!' into top-block module '!%2!'.!%3!\n";
    gid = "90-5";
    id = "4";
    key = "Failed to split sub-block instance '%s' into top-block module '%s'.%s\n";
    modified_format_str = "@90-5@%s%s%s";
    notes = "";
    owner = "brianc";
    reference_cnt = "1";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "CRITICALWARNING";
    tags = "";
  },
  {
    description = "";
    format = "Failed to validate top block '!%1!'.!%2!\n";
    gid = "90-6";
    id = "5";
    key = "Failed to validate top block '%s'.%s\n";
    modified_format_str = "@90-6@%s%s";
    notes = "";
    owner = "brianc";
    reference_cnt = "28";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "ERROR";
    state = "changed";
    tags = "";
  },
  {
    description = "";
    format = "Failed to write file '!%1!'.\n";
    gid = "90-7";
    id = "6";
    key = "Failed to write file '%s'.\n";
    modified_format_str = "@90-7@%s";
    notes = "";
    owner = "brianc";
    reference_cnt = "3";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "ERROR";
    tags = "";
  },
  {
    description = "";
    format = "JSON object '!%1!' contains unexpected field of type '!%2!'.\n";
    gid = "90-8";
    id = "7";
    key = "JSON object '%s' contains unexpected field of type '%s'.\n";
    modified_format_str = "@90-8@%s%s";
    notes = "";
    owner = "brianc";
    reference_cnt = "3";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "ERROR";
    tags = "";
  },
  {
    description = "";
    format = "JSON object is missing mandatory field '!%1!'.\n";
    gid = "90-9";
    id = "8";
    key = "JSON object is missing mandatory field '%s'.\n";
    modified_format_str = "@90-9@%s";
    notes = "";
    owner = "brianc";
    reference_cnt = "1";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "ERROR";
    tags = "";
  },
  {
    description = "";
    format = "Provisionally validated top block '!%1!'.!%2!\n";
    gid = "90-10";
    id = "9";
    key = "Provisionally validated top block '%s'.%s\n";
    modified_format_str = "@90-10@%s%s";
    notes = "";
    owner = "rkunwar, brianc";
    reference_cnt = "8";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "CRITICALWARNING";
    tags = "";
  }
);
subsystem_alias = "ModularNoC";
version = "4";
