messages =
(
  {
    description = "";
    format = "HBSClockingAlgo6Pll::runSolution Input freq: !%1! Requested freq.: !%2! \n\t\ttotal_related_error: !%3! tolerance level: !%4! Time taken (milliseconds): !%5!\n";
    gid = "91-42";
    id = "1";
    key = "HBSClockingAlgo6Pll::runSolution Input freq: %f Requested freq.: %d \n\t\ttotal_related_error: %f tolerance level: %f Time taken (milliseconds): %d\n";
    modified_format_str = "@91-42@%f%d%f%f%d";
    notes = "";
    owner = "dinesha, msgrole";
    reference_cnt = "2";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "INFO";
    tags = "";
  },
  {
    description = "";
    format = "Failed to merge Hard Block definition '!%1!' into Hard Block instance '!%2!'.\n";
    gid = "91-44";
    id = "2";
    key = "Failed to merge Hard Block definition '%s' into Hard Block instance '%s'.\n";
    modified_format_str = "@91-44@%s%s";
    notes = "";
    owner = "brianc";
    reference_cnt = "1";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "ERROR";
    tags = "";
  },
  {
    description = "";
    format = "Failed to read Hard Block definition '!%1!'.\n";
    gid = "91-45";
    id = "3";
    key = "Failed to read Hard Block definition '%s'.\n";
    modified_format_str = "@91-45@%s";
    notes = "";
    owner = "brianc";
    reference_cnt = "1";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "ERROR";
    tags = "";
  },
  {
    description = "";
    format = "Found invalid key '!%1!'. Valid keys are: '!%2!'.\n";
    gid = "91-48";
    id = "4";
    key = "Found invalid key '%s'. Valid keys are: '%s'.";
    modified_format_str = "@91-48@%s%s";
    notes = "";
    owner = "";
    reference_cnt = "1";
    resolution = "";
    review_date = "";
    reviewer = "";
    severity = "ERROR";
    state = "new";
    tags = "";
  }
);
subsystem_alias = "Hbs";
version = "4";
